### ISSUE TITLE
Help menu gives errors

### ISSUE THREAD

**Issue by StefanJanssen95** [tingbot/tide-electron#46]
I'm using v0.3.1 which is currently available as beta on the website. When I open the help menu and click one of the 2 options (Tingbot Forum or Tingbot Documentation) it gives me an error.

```
A javascript error occurred in the main process
Uncaught Exception:
ReferenceError: shell is not defined
  at click (location of app.js:314:41)
  at MenuItem.click (electron api path)
  at Function.executeCommand (electron api path)
```

This is what I get on Windows 10, don't know if the same happens on other OS's.

**Comment by xtramural** [comment]
I'm using v0.3.3 on Mac OSX 10.9.5 and get a similar error:

```
Uncaught Exception:
ReferenceError: shell is not defined
    at click (/Applications/Tide.app/Contents/Resources/app/app.js:314:41)
    at MenuItem.click (/Applications/Tide.app/Contents/Resources/electron.asar/browser/api/menu-item.js:59:9)
    at Function.executeCommand (/Applications/Tide.app/Contents/Resources/electron.asar/browser/api/menu.js:121:15)
```

**Comment by joerick** [comment]
Looks like a missing import from the Electron framework. Should be an easy fix. PRs welcome!

**Comment by joerick** [comment]
:+1: thanks guys!
