### ISSUE TITLE
Tide run on Mint 18 only under root.

### ISSUE THREAD

**Issue by KirillChubarov** [tingbot/tide-electron#63]
After installing Tide .deb with GDebi on Mint 18 it can run only from root, and wan't run from regular user.

~ $ Tide
module.js:442
    throw err;
    ^

Error: Cannot find module '/opt/Tide/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:360:7)
    at startup (bootstrap_node.js:152:9)
    at bootstrap_node.js:479:3

**Comment by joerick** [comment]
Any ideas on this @Rob4001?
