### ISSUE TITLE
Unable to launch on Ubuntu

### ISSUE THREAD

**Issue by ir-g** [tingbot/tide-electron#67]
I'm on Ubuntu 16.04 LTS, and when I attempt to launch tide, the application appears to start launching(appears in app dock on left), and then disappears. While, this works well for me on Windows, it is frustrating that this sint working for me on Linux. Are there any know helpers/solutions to this problem?

**Comment by joerick** [comment]
Hey ir-g, I've not heard of this one before. Sounds like it's crashing before it has a chance to boot up. Would you be able to get some logs of the crash somehow? Perhaps you could start Tide from a terminal window?

**Comment by ir-g** [comment]
I haven't figured out how to start Tide from the terminal window, though
for some days have been trying. Where abouts would the executable be
located once installed in Ubuntu/Debian?

**Comment by joerick** [comment]
I don't know, I'm not really a Linux guy!

Any Ubuntu users please chime in!

**Comment by ir-g** [comment]
I've just mangaged to find where tide is installed for me: `/opt/Tide`.
_Location of tide was found via `dpkg -L tide`._

When running, I get:
```
module.js:442
    throw err;
    ^

Error: Cannot find module '/opt/Tide/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:360:7)
    at startup (bootstrap_node.js:152:9)
    at bootstrap_node.js:479:3
```

This is because the `/opt/Tide/resources` directory requires Sudo(admin) access to Read/Write/etc to. As a brute force solution. I did the following.

```sh
cd /opt/Tide
sudo chmod -R 777 resources/
```

This makes the `/opt/Tide/resources` readable and writeable to **anyone**. More fine-tuned permissions should be used in any realistic scenario, but that was the source of the issue.

**Comment by chrisbeardy** [comment]
@ir-g I had the same issue here, your solution worked for me too.
