### ISSUE TITLE
Cannot lauch Tide on Linux

### ISSUE THREAD

**Issue by EisFrei** [tingbot/tide-electron#76]
Used Package: https://github.com/tingbot/tide-electron/releases/download/v0.5.7/Tide-0.5.7-amd64.deb

When trying to launch Tide it just throws an error, which appears to be a problem with the electron builder used:
https://github.com/electron-userland/electron-builder/issues/2958

```
$ Tide
module.js:442
    throw err;
    ^

Error: Cannot find module '/opt/Tide/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:360:7)
    at startup (bootstrap_node.js:152:9)
    at bootstrap_node.js:479:3

```

**Comment by chrisbeardy** [comment]
see issue #67 , its about permissons for the resources folder, that seems to solve it

**Comment by billkouts** [comment]
Hello! I am also unable to make Tide work on linux.
I am using Ubuntu 20.04
I have downloaded the deb package from [here](https://github.com/tingbot/tide-electron/releases)
I double clicked the deb file which opens the **Ubuntu Software** app to perform the install
The **Ubuntu Software** then gets stuck on starting up 
![Screenshot from 2020-11-14 14-52-29](https://user-images.githubusercontent.com/26868617/99149936-0c14d900-2689-11eb-94f1-781e5692bf47.png)

It looks like its a different problem to the OPs, if that is the case let me know and i can open a new issue.

**Comment by billkouts** [comment]
I tried installing from the terminal, and I got the following:
```python
(Reading database ... 201300 files and directories currently installed.)
Preparing to unpack Tide-0.5.8-amd64.deb ...
Unpacking tide (0.5.8-173) over (0.5.8-173) ...
dpkg: dependency problems prevent configuration of tide:
 tide depends on python2.7; however:
  Package python2.7 is not installed.
 tide depends on python-cryptography; however:
  Package python-cryptography is not installed.

dpkg: error processing package tide (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Errors were encountered while processing:
 tide
```

So it looks like it needs a specific version of python (python2.7) which is not there, plus one dependency (python-cryptography)
Considering python 2 is officially terminated, do you think that providing a new version of Tide that uses python 3 is possible?

**Comment by joerick** [comment]
Hey @billkouts ! You might try installing those dependencies manually, it's possible they're still available via `apt`.

As for Python 3… Upgrading Tide to use it would be one part, you'd also need to update tingbot-python to use it, and the Tingbot OS, if you're using the hardware too. It's not something that I have time for at the moment, but everything is open source, so feel free to give it a go yourself if you're interested. I'm happy to provide pointers if needed.
